Changed and added files according to Telegram Updated Repo
dream-aim-deliver/mpi-sda-twitter-scraper pull request #4
Opened 2024-04-04 07:55 UTC by iamMihirT

2024-04-04 11:11 UTC, maany commented on tests/test_scraper.py
> +import telegram_scraper
import twitter scraper

2024-04-07 12:44 UTC, maany requested changes
Please make it command line executable, fix the requirements, leave the server.py as it is ( on second thought, I will fix it for all the data pipelines later). Think of how to ensure the pipelines scrape all data, handle rate limits, etc. Use geo features if possible.

2024-04-07 12:44 UTC, maany commented on app/scraper.py
> +                            "content": f"Examine this tweet: {tweet['snippet']}. Is this tweet describing {filter_keyword}? "
not defined

2024-04-07 12:44 UTC, maany commented on app/scraper.py
> +from logging import Logger
you need to include instructor, pandas, openai, pydantic, requests in your requirements.txt

2024-04-07 12:44 UTC, maany commented on app/scraper.py
> +                    scraped_data_repository.register_scraped_data(
function does not exist

2024-04-09 10:06 UTC, iamMihirT commented
We still have doubts regarding the usage and importing of scraping api key. Also this version does version is not yet updated with openai. We are facing trouble in replicating what is shown in the video.
But we have kept all of the code similar to telegram.

2024-04-14 18:06 UTC, maany commented
Merging as is to unblock integration into kubeflow pipelines. Please test this and send follow up PRs ASAP.

2024-04-14 18:07 UTC, maany commented
Make sure requirements.txt is up to date

2024-04-14 18:07 UTC, merged